#!/bin/bash
#/etc/init.d/subwifi.sh

# this script should be placed in /etc/init.d/
#see https://www.debian-administration.org/article/28/Making_scripts_run_at_boot_time_with_Debian

# Some things that run always
#touch /var/lock/blah

case "$1" in
  start)
    /root/wifi.sh >> /root/wifi.log
    ;;
  stop)
    killall wifi.sh
    ;;
  *)
    echo "Usage: /etc/init.d/subwifi {start|stop}"
    exit 1
    ;;
esac

exit 0
